CREATE TABLE "public"."accounts" (
  "id"               bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"          uuid                     NOT NULL,
  "name"             text                     NOT NULL,
  "starting_balance" numeric                  NOT NULL,
  "currency"         text                     NOT NULL,
  "broker"           text,
  "account_type"     text,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "accounts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."accounts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."demo_state" (
  "id"               bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "user_id"          uuid                     NOT NULL,
  "last_activity_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "demo_state_pkey" PRIMARY KEY (id),
  CONSTRAINT "demo_state_user_id_key" UNIQUE (user_id)
);

ALTER TABLE "public"."demo_state"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."trades" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "symbol"         text                     NOT NULL,
  "direction"      text                     NOT NULL,
  "entry"          numeric                  NOT NULL,
  "stop"           numeric,
  "exit"           numeric                  NOT NULL,
  "result"         numeric,
  "created_at"     timestamp with time zone DEFAULT now(),
  "entry_datetime" timestamp with time zone NOT NULL,
  "exit_datetime"  timestamp with time zone NOT NULL,
  "user_id"        uuid,
  "account_id"     bigint                   NOT NULL,
  "pnl"            double precision         NOT NULL,
  CONSTRAINT "trades_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."trades"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."accounts"
  ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."demo_state"
  ADD CONSTRAINT "demo_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."trades"
  ADD CONSTRAINT "trades_account_id_fkey" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;

CREATE POLICY "Users can create own accounts" ON "public"."accounts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete own accounts" ON "public"."accounts"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update own accounts" ON "public"."accounts"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view own accounts" ON "public"."accounts"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Demo user can read own state" ON "public"."demo_state"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Demo user can update own state" ON "public"."demo_state"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can delete own trades" ON "public"."trades"
  FOR DELETE
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can insert own trades" ON "public"."trades"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.accounts
  WHERE ((accounts.id = trades.account_id) AND (accounts.user_id = auth.uid()))))));

CREATE POLICY "Users can read own trades" ON "public"."trades"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update own trades" ON "public"."trades"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1
   FROM public.accounts
  WHERE ((accounts.id = trades.account_id) AND (accounts.user_id = auth.uid()))))));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."accounts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."demo_state" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."trades" TO "anon", "authenticated", "postgres", "service_role";